version: "3"

services:
    # nginx:
    #     image: nginx
    #     restart: always
    #     ports:
    #         - "80:80"
    #     volumes:
    #         - ./config/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
    #     depends_on:
    #         - node-app
    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: bash -c "npm start" 
        ports:
            - "3000:3000"
        expose: 
            - "3000"    